/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.CRUD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author riqqi
 */
public class PanelLaporan extends javax.swing.JPanel {

   CRUD crud;
   int idAkun;

   /**
    * Creates new form PanelLaporan
    */
   public PanelLaporan(int idAkun, CRUD crud) {
      this.crud = crud;
      this.idAkun = idAkun;
      initComponents();
   }

   public void insertListAkun() {
      ResultSet nominal = crud.ambilData("SELECT * FROM akun");
      cb = new DefaultComboBoxModel<String>();
      try {
         cb.addElement("---pilih---");
         while (nominal.next()) {
            String nominalRp = crud.integerToRupiah(Integer.parseInt(nominal.getString("harga")));
            cb.addElement(nominalRp);
         }
         cbNominal.setModel(cb);
      } catch (SQLException ex) {
         Logger.getLogger(PanelTransJual.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      cbAkun = new javax.swing.JComboBox();

      cbAkun.setBorder(javax.swing.BorderFactory.createTitledBorder("Akun"));
      cbAkun.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            cbAkunFocusLost(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(cbAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(784, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(cbAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(245, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void cbAkunFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbAkunFocusLost
   }//GEN-LAST:event_cbAkunFocusLost

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox cbAkun;
   // End of variables declaration//GEN-END:variables
}
